[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
usdt_test = "G1C8yBLEFGAHYy59zd8ce9aYF7jZDJyegzGptgoLdYyy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
